name: Create a new session abstract
description: Create me to create a new session abstract.
title: "[Abstract]: "
labels: ["abstract"]
assignees:
  - MatthijsvdVeer
body:
  - type: textarea
    id: audience
    attributes:
      label: "1. Who do you think this talk is for?"
      description: Identify the target audience for this talk.
      placeholder: "Developers, Consultants, Data Scientists, etc."
    validations:
      required: true
  - type: textarea
    id: learning_outcomes
    attributes:
      label: "2. What do you think you'll learn from this talk?"
      description: Describe what knowledge or skills you expect to gain.
      placeholder: "This talk will get you started with Azure OpenAI. You will learn how to use the API to generate text."
    validations:
      required: true
  - type: textarea
    id: accomplishments
    attributes:
      label: "3. What's something you'll be able to accomplish with the information gained from this talk?"
      description: Explain how you can apply the information from this talk.
      placeholder: "You will be able to generate text using the Azure OpenAI API."
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: "4. What is the two-sentence summary of the talk?"
      description: Provide a brief summary of the talk's content.
      placeholder: "This talk will introduce you to the Azure OpenAI API and show you how to generate text using the API."
    validations:
      required: true
